apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      imagePullSecrets:
        - name: ecr-secrets
      serviceAccountName: clo835-group  # Assign the created ServiceAccount
      containers:
        - name: mysql
          image: 911048994404.dkr.ecr.us-east-1.amazonaws.com/db-repository:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-database
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
