apiVersion: v1
kind: ServiceAccount
metadata: 
  name: clo835-group
  namespace: final  # Specify the namespace here
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::911048994404:role/LabRole